### ISSUE TITLE
Fixing the black screen error when starting the graphical environment

### ISSUE THREAD

**Issue by PEDROTUBER44** [PEDROTUBER44/Mild#2]
To fix this "error" select the desktop environment you installed and which will be started by clicking:

### GDM

![](https://tlgur.com/d/GXjPVZJ4)

### Lightdm

![](https://tlgur.com/d/GVqVdXm8)

### SDDM

![](https://tlgur.com/d/GPq5x1Vg)

**Comment by PEDROROSENDO1** [comment]
This issue has been fixed by the developers themselves
